name: remix-publish-action
on:
  pull_request:
    types: [ labeled ]
jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install     
      - run: ls
      - run: pwd
      - run: npm run downloadsolc_assets
      - run: npm run build:production
      - run: ./apps/remix-ide/ci/copy_resources.sh     
      - run: ./apps/remix-ide/ci/publishIpfs