name: remix-publish-action
on:
  pull_request:
    types: [ labeled ]
jobs:
  build:
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - run: cd ..
     - run: npm install     
     - run: ls
     - run: pwd
     - run: nx build remix-ide --with-deps
     - run: node ./apps/remix-ide/ci/publishIpfs
