 on:
  check_run:
    types:
      # Check runs completing successfully can unblock the
      # corresponding pull requests and make them mergeable.
      - completed
  pull_request:
    types:
      # A closed pull request makes the checks on the other
      # pull request on the same base outdated.
      - closed
  pull_request_review:
    types:
      # Review approvals can unblock the pull request and
      # make it mergeable.
      - submitted
  # Success statuses can unblock the corresponding
  # pull requests and make them mergeable.
  status: {}
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != ''
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
